### ISSUE TITLE
Footer missing logo

### ISSUE THREAD

**Issue by jamesdoc** [theglobechurch/globe-static#2]
In the designs the desktop view has a church logo in it, rotated to the side. This needs to be implemented
<img width="555" alt="Footer layout" src="https://user-images.githubusercontent.com/790343/201857841-cb30bef8-0a1a-44fe-9a46-dec69e8f1130.png">

Icon can be pulled in with the following (second var is for CSS classes)

```
{% svgIcon "tgcLogoOutline", "w-full" %}
```

Note that this is for desktop only, not mobile

**Comment by MazOneTwoOne** [comment]
Closed
